### PR TITLE
Add New ECL Snippets

### PR DESCRIPTION
**Pull request by newportm**
Added most of the commonly used STD library, data types, function and macro templates, and a few reserved function grouping including dedup and join.

### CODE REVIEW

**Comment by GordonSmith** [comment]
I suspect folks are going to like this.

Question:  Should these be added to - https://github.com/hpcc-systems/vscode-ecl/blob/master/snippets/ecl.json

Which is already getting pulled in via:  https://github.com/hpcc-systems/vscode-ecl/blob/master/package.json#L145-L149

**Comment by newportm** [comment]
@GordonSmith We can definitly add it to the existing json file. I was not sure where it was being stored in relation to the ECL Language Extension ... so I created my own user snippet file that I could reference and test. Full disclosure, I have not had time to test every call. This is a WIP but I figured at this point something is better than nothing for a lot of people. I will add more as time goes on and test each time permitting.

**Comment by GordonSmith** [comment]
If you happy that "something is better than nothing" I will go ahead and merge into the existing file and push a release?

**Comment by newportm** [comment]
@GordonSmith I went ahead and did the merge with ecl.json. Go ahead and release and I will do a quick sanity check to make sure the additions are showing up. I will keep tweaking this and push up commits as I expand the functionality.

**Comment by GordonSmith** [comment]
Sounds good - just going to review the latest VSCode docs on snippets in case we are missing a trick.

**Comment by GordonSmith** [comment]
Closing in favour of:  https://github.com/hpcc-systems/vscode-ecl/pull/172

**Pull request closed without merging**
