### PR TITLE
feat: Add right-click menus to Bundles and Client Tools

### LINKED ISSUE #360: Add right-click menus for inline context for Bundles and Client Tools view
Replicate the inline context menu items as right-click menus in Bundles and Client Tools.

### PR DESCRIPTION
**Pull request by dehilsterlexis**
Fixes #360

### CODE REVIEW

**Comment by dehilsterlexis** [comment]
@GordonSmith for review

**Review by GordonSmith — APPROVED** [review]
Code looks good, just the commit msg + title need to be tweaked.

**Comment by dehilsterlexis** [comment]
@GordonSmith changed as requested

**Comment by GordonSmith** [comment]
@dehilsterlexis - For future reference it needs to be on the commit msg and not this PR title (which is why it didn't show up in the changelog)...

**Pull request merged**
